---
all:
  vars:
    ansible_user:               admin
    ansible_python_interpreter: /usr/bin/python3
  children:  
    masters:
      hosts:
        master-0:
          ansible_host: master-0
        master-1:
          ansible_host: master-1
        master-2:
          ansible_host: master-2
      vars: 
        public_ip: "{{ lookup('dig', ansible_host) }}"
        public_fqdn: "{{ ansible_host }}"
        public_hostname: "{{ ansible_hostname }}"
    etcd:
        children:
            masters  
    nodes:
      hosts:
        node-0:
          ansible_host: node-0
          cni_host_subnet: "192.168.1.0/24"
        node-1:
          ansible_host: node-1
          cni_host_subnet: "192.168.2.0/24"
        node-2:
          ansible_host: node-2
          cni_host_subnet: "192.168.3.0/24"
      vars: 
        public_ip: "{{ lookup('dig', ansible_host) }}"
        public_fqdn: "{{ ansible_host }}"
        public_hostname: "{{ ansible_hostname }}"
